#!/bin/sh

ALERTS=$(cat /tmp/gh-notify.txt)

if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
  # wifi
  cd ./scripts/gh-notify && ./gh-notify
  sleep 1s;
  echo "  $ALERTS"
else
  # no wifi
  echo "  Connecting to Github..."
fi
