#!/bin/sh

ALERTS=$(cat /tmp/gh-notify.txt)
WIFI=$(cat /sys/class/net/w*/operstate 2>/dev/null)

case "$WIFI" in

  up)
    cd ./scripts/gh-notify && ./gh-notify
    status="  $ALERTS"
    ;;

  down)
    status="  Connecting to Github...\n"
    ;;

esac

printf "%s\n" "$status"
